# Raspberry Pi configuration
#CONFIG_RASPBERRY_PI=1

#CFLAGS:=-DCONFIG_RASPBERRY_PI=1

# PC configuration
CONFIG_PC=1
CONFIG_PULSE_AUDIO=1
CONFIG_VIDEO=1
CONFIG_OPENGL_VIDEO=1
#CONFIG_SDL2_VIDEO=1

CFLAGS:=-DCONFIG_PC=1 
CFLAGS+=-DCONFIG_PULSE_AUDIO=1
CFLAGS+=-DCONFIG_OPENGL_VIDEO=1
#CFLAGS+=-DCONFIG_SDL2_VIDEO=1
CFLAGS+=-DCONFIG_VIDEO=1
